import { JSON_CONTRACT_VERSION } from '../lib/output.js';

export function getCapabilitiesManifest(version: string) {
  return {
    cli_name: 'sidecar',
    cli_version: version,
    json_contract_version: JSON_CONTRACT_VERSION,
    features: [
      'json_envelope_v1',
      'capabilities_manifest',
      'event_ingest',
      'export_json',
      'export_jsonl_events',
      'optional_local_ui',
    ],
    commands: [
      {
        name: 'init',
        description: 'Initialize Sidecar in the current directory',
        json_output: true,
        arguments: [],
        options: ['--force', '--name <project-name>', '--json'],
      },
      {
        name: 'status',
        description: 'Show Sidecar initialization status and activity counts',
        json_output: true,
        arguments: [],
        options: ['--json'],
      },
      {
        name: 'preferences',
        description: 'Preferences operations',
        json_output: true,
        arguments: [],
        options: [],
        subcommands: [
          {
            name: 'show',
            description: 'Show project preferences',
            json_output: true,
            arguments: [],
            options: ['--json'],
          },
        ],
      },
      {
        name: 'ui',
        description: 'Launch optional local Sidecar UI (lazy-installed on first run)',
        json_output: false,
        arguments: [],
        options: ['--no-open', '--port <port>', '--install-only', '--project <path>', '--reinstall'],
      },
      {
        name: 'capabilities',
        description: 'Show machine-readable CLI manifest',
        json_output: true,
        arguments: [],
        options: ['--json'],
      },
      {
        name: 'context',
        description: 'Generate project context snapshot',
        json_output: true,
        arguments: [],
        options: ['--limit <n>', '--format text|markdown|json', '--json'],
      },
      {
        name: 'event',
        description: 'Generic event ingest operations',
        json_output: true,
        arguments: [],
        options: [],
        subcommands: [
          {
            name: 'add',
            description: 'Add a validated generic event payload',
            json_output: true,
            arguments: [],
            options: [
              '--type <type>',
              '--title <title>',
              '--summary <summary>',
              '--details-json <json>',
              '--created-by <by>',
              '--source <source>',
              '--session-id <id>',
              '--json-input <json>',
              '--stdin',
              '--json',
            ],
          },
        ],
      },
      {
        name: 'export',
        description: 'Export project memory in JSON or JSONL',
        json_output: true,
        arguments: [],
        options: ['--format json|jsonl', '--limit <n>', '--type <event-type>', '--since <iso-date>', '--until <iso-date>', '--output <path>', '--json'],
      },
      {
        name: 'summary',
        description: 'Summary operations',
        json_output: true,
        arguments: [],
        options: [],
        subcommands: [
          {
            name: 'refresh',
            description: 'Regenerate .sidecar/summary.md',
            json_output: true,
            arguments: [],
            options: ['--limit <n>', '--json'],
          },
        ],
      },
      {
        name: 'recent',
        description: 'Show recent event timeline',
        json_output: true,
        arguments: [],
        options: ['--type <event-type>', '--limit <n>', '--json'],
      },
      {
        name: 'note',
        description: 'Record a note event',
        json_output: true,
        arguments: ['<text>'],
        options: ['--title <title>', '--by human|agent', '--session <id>', '--json'],
      },
      {
        name: 'decision',
        description: 'Decision operations',
        json_output: true,
        arguments: [],
        options: [],
        subcommands: [
          {
            name: 'record',
            description: 'Record a decision',
            json_output: true,
            arguments: [],
            options: ['--title <title>', '--summary <summary>', '--details <details>', '--by human|agent', '--session <id>', '--json'],
          },
        ],
      },
      {
        name: 'worklog',
        description: 'Worklog operations',
        json_output: true,
        arguments: [],
        options: [],
        subcommands: [
          {
            name: 'record',
            description: 'Record a worklog',
            json_output: true,
            arguments: [],
            options: ['--goal <goal>', '--done <summary>', '--files <paths>', '--risks <text>', '--next <text>', '--by human|agent', '--session <id>', '--json'],
          },
        ],
      },
      {
        name: 'task',
        description: 'Task operations',
        json_output: true,
        arguments: [],
        options: [],
        subcommands: [
          {
            name: 'add',
            description: 'Create an open task',
            json_output: true,
            arguments: ['<title>'],
            options: ['--description <text>', '--priority low|medium|high', '--by human|agent', '--json'],
          },
          {
            name: 'done',
            description: 'Mark a task as done',
            json_output: true,
            arguments: ['<task-id>'],
            options: ['--by human|agent', '--json'],
          },
          {
            name: 'list',
            description: 'List tasks',
            json_output: true,
            arguments: [],
            options: ['--status open|done|all', '--format table|json', '--json'],
          },
        ],
      },
      {
        name: 'session',
        description: 'Session operations',
        json_output: true,
        arguments: [],
        options: [],
        subcommands: [
          {
            name: 'start',
            description: 'Start a session',
            json_output: true,
            arguments: [],
            options: ['--actor human|agent', '--name <actor-name>', '--json'],
          },
          {
            name: 'end',
            description: 'End the active session',
            json_output: true,
            arguments: [],
            options: ['--summary <text>', '--json'],
          },
          {
            name: 'current',
            description: 'Show active session',
            json_output: true,
            arguments: [],
            options: ['--json'],
          },
          {
            name: 'verify',
            description: 'Run lightweight session hygiene checks',
            json_output: true,
            arguments: [],
            options: ['--json'],
          },
        ],
      },
      {
        name: 'doctor',
        description: 'Alias for session verify',
        json_output: true,
        arguments: [],
        options: ['--json'],
      },
      {
        name: 'artifact',
        description: 'Artifact operations',
        json_output: true,
        arguments: [],
        options: [],
        subcommands: [
          {
            name: 'add',
            description: 'Add an artifact reference',
            json_output: true,
            arguments: ['<path>'],
            options: ['--kind file|doc|screenshot|other', '--note <text>', '--json'],
          },
          {
            name: 'list',
            description: 'List recent artifacts',
            json_output: true,
            arguments: [],
            options: ['--json'],
          },
        ],
      },
    ],
  };
}
